import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import Script from "next/script";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "فلیپ مارت - قالب پرمیوم فروشگاهی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/bootstrap-rtl.min.css" />
        <link rel="stylesheet" href="/assets/css/main.css" />
        <link rel="stylesheet" href="/assets/css/blue.css" />
        <link rel="stylesheet" href="/assets/css/owl.carousel.css" />
        <link rel="stylesheet" href="/assets/css/owl.transitions.css" />
        <link rel="stylesheet" href="/assets/css/animate.min.css" />
        <link rel="stylesheet" href="/assets/css/rateit.css" />
        <link rel="stylesheet" href="/assets/css/bootstrap-select.min.css" />
        <link rel="stylesheet" href="/assets/css/font-awesome.css" />
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Layout>{children}</Layout>
        </ThemeProvider>

        <Script src="/assets/js/jquery-1.11.1.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/bootstrap.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/bootstrap-hover-dropdown.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/owl.carousel.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/echo.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/jquery.easing-1.3.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/bootstrap-slider.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/jquery.rateit.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/lightbox.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/bootstrap-select.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/wow.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/scripts.js" strategy="beforeInteractive" />
      </body>
    </html>
  );
}
